### ISSUE TITLE
[BUG] Circular dependency between `imio` and `brainglobe-utils` 

### ISSUE THREAD

**Issue by willGraham01** [brainglobe/BrainGlobe#64]
https://github.com/brainglobe/brainglobe-utils/pull/22 introduced a circular dependency between  `brainglobe-utils` and `imio`: `imio` needs `brainglobe-utils`, whilst `brainglobe-utils` now needs `imio` due to the functionality that was refactored into it.

Needless to say, this is not ideal. On the surface everything "still works" since there are no circular _imports_, but naturally we probably want to fix this sooner rather than later.

Zulip discussion: https://brainglobe.zulipchat.com/#narrow/stream/408841-development/topic/.60imio.60.20and.20.60brainglobe-utils.60.20circular.20dependency/near/419020085

## Task List (merge [`imio`](https://github.com/brainglobe/imio) into [`brainglobe-utils`](https://github.com/brainglobe/brainglobe-utils))

- [x] Mark `imio` as depreciated with a suitable PR https://github.com/brainglobe/imio/pull/55
  - [x] Release final version to PyPI
  - [x] Transfer issues to `brainglobe-utils` with a suitable label
  - [x] Archive `imio` repository
- [x] Prepare merge branch in `brainglobe-utils` https://github.com/brainglobe/brainglobe-utils/pull/33
  - [x] Release new version to PyPI, at least v0.4.0!
- [ ] Update packages that used to depend on `imio`
  - [x] `brainglobe-segmentation` gains a `brainglobe-utils` dependency | https://github.com/brainglobe/brainglobe-segmentation/pull/168 | new version 1.2.2
  - [x] `brainreg` drops its `imio` dependency as it already depends on `brainglobe-utils` | https://github.com/brainglobe/brainreg/pull/181 | new version 1.0.5
  - [x] Release new versions of updated packages
  - [ ] Release new metapackage version with pinned dependencies | https://github.com/brainglobe/brainglobe-meta/pull/47
- [x] Stage update to documentation website https://github.com/brainglobe/brainglobe.github.io/pull/149
  - [x] Blog post with `imio` move
  - [x] Documentation updates
    - [x] Dependency graph update
    - [x] Move any imio documentation into `brainglobe-utils` docs
- [x] Update https://github.com/brainglobe/brainglobe-meta/issues/40 task plan to account for `imio` package no longer being used.

**Comment by willGraham01** [comment]
As agreed in the developer meeting on 08-02-2024, we will be merging `imio` into `brainglobe-utils` as a submodule.

Task list with updates has been added to the main issue comment for tracking.
